### ISSUE TITLE
MSMR does not register xTrs

### ISSUE THREAD

**Issue by iraponomareva** [farinacci/lispers.net#18]
Please help me figure out what the problem is. I have assembled a small stand for LISP in Docker containers. I set all the settings, it seems, correctly, but map-server does not see xTrs. 

Here is my configuration for ms:

lisp enable {
    itr = no
    etr = no
    rtr = no
    map-server = yes
    map-resolver = yes
    ddt-node = no
}
lisp debug {
    etr = no
    core = no
    map-resolver = yes
    ddt-node = no
    rtr = no
    map-server = yes
    itr = no
}
lisp user-account {
    username = root
    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
    super-user = yes
}
lisp interface {
    interface-name = 0_rloc
    device = eth1
}
lisp site {
    site-name = site-1
   authentication-key = any-key
    allowed-prefix {
        accept-more-specifics = yes
        eid-prefix = 192.168.1.0/24
    }
   allowed-rloc {
        address = 10.0.0.3
        priority = 1
        weight = 50
    }
}
lisp site {
    site-name = site-2
    shutdown = yes
    authentication-key = some-key
    allowed-prefix {
        accept-more-specifics = yes
        eid-prefix = 192.168.2.0/24
    }
   allowed-rloc {
        address = 10.0.0.4
        priority = 1
        weight = 50
    }
}

And this is the configuration for xTr:

lisp enable {
    itr = yes
    etr = yes
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp debug {
    core = no
    itr = no
    etr = no
    rtr = no
    map-server = no
    map-resolver = no
    ddt-node = no
}
lisp user-account {
    username = root
    password = =b9e5c39708999f844a3c864e863c12618bf8a3f5
    super-user = yes
}
lisp xtr-parameters {
    rloc-probing = no
    data-plane-security = no
    nonce-echoing = no
    nat-traversal = no
    flow-logging = no
    data-plane-logging = yes
}
lisp interface {
    interface-name = 0_rloc
    device = eth1
}
lisp interface {
    interface-name = 2_eid
    device = eth2
}
lisp map-resolver {
    mr-name = my-mr
    address = 10.0.0.2
}
lisp map-server {
    ms-name = my-ms
    address = 10.0.0.2
    authentication-key = some-key
}
lisp database-mapping {
    prefix {
        eid-prefix = 192.168.2.0/24
    }
    rloc {
        address = 10.0.0.4
        priority = 1
        weight = 50
    }
}

**Comment by farinacci** [comment]
Try removing the "eid-prefix" and "allowed-rloc" from your "lisp site" clause so both EID and RLOCs can be dynamic. That will optimize your configuration to allow new EIDs to come into service as well as the dynamic binding from EID-to-RLOC to change.

**Comment by iraponomareva** [comment]
thank you very much

**Comment by iraponomareva** [comment]
Hello, it seems the problem is not with the settings, but with the web interface. 
I checked with tcpdump the path of the ping message, from eid1 to eid2. tcpdump displays that the address request with msmr passes, and all request-replay and register messages are also there. But the ms interface shows that the lisp-site is not registered.

**Comment by farinacci** [comment]
Send me output from lisp-ms.log on the map-server. Dino On Nov 18, 2022, at 10:22 PM, iraponomareva ***@***.***> wrote:﻿
Hello, it seems the problem is not with the settings, but with the web interface.
I checked with tcpdump the path of the ping message, from eid1 to eid2. tcpdump displays that the address request with msmr passes, and all request-replay and register messages are also there. But the ms interface shows that the lisp-site is not registered.

**Comment by iraponomareva** [comment]
Thank you, I have solved this problem

**Comment by farinacci** [comment]
Great to hear. Please send me your progress and what your deployment/test plans are. Unicast to ***@***.*** Thanks. DinoOn Nov 21, 2022, at 9:25 PM, iraponomareva ***@***.***> wrote:﻿
Thank you, I have solved this problem

**Comment by iraponomareva** [comment]
At the moment I have assembled a stand of 5 dockers: 2 eid, 2 xtr and msmr. Configured routing using the LISP protocol. Now I want to try LISP host mobility. While it was not possible to launch the stand with the relocation of the host, I do not understand what the problem is, I used lisp.config.xtr-mobility for settings,  I'm trying to figure out where I made a mistake.

**Comment by iraponomareva** [comment]
if I manage to launch LISP host mobility, I plan to try scaling the model by adding devices to it (end-point, xtr's and ms, maybe non-lisp-site). I want to see the capabilities of the protocol, since I am writing a dissertation on routing

**Comment by farinacci** [comment]
If you do not see the EID discovered on the xTR you moved the host to it is likely that the docket logical interface may not be connected to the moved-to xTR. Check lisp-itr.log to see if the xTR sees packets from the moving host container. You need to turn on itr=yes under “lisp debug” and data-plane-logging=yes under “lisp xtr-parameters”. DinoOn Nov 22, 2022, at 8:23 PM, iraponomareva ***@***.***> wrote:﻿
At the moment I have assembled a stand of 5 dockers: 2 eid, 2 xtr and msmr. Configured routing using the LISP protocol. Now I want to try LISP host mobility. While it was not possible to launch the stand with the relocation of the host, I do not understand what the problem is, I used lisp.config.xtr-mobility for settings,  I'm trying to figure out where I made a mistake.

**Comment by farinacci** [comment]
Sounds good. When you try interworking to non-lisp sites, make sure you enable lisp-nat=yes under “lisp interface”. DinoOn Nov 22, 2022, at 8:27 PM, iraponomareva ***@***.***> wrote:﻿
if I manage to launch LISP host mobility, I plan to try scaling the model by adding devices to it (end-point, xtr's and ms, maybe non-lisp-site). I want to see the capabilities of the protocol, since I am writing a dissertation on routing

**Comment by iraponomareva** [comment]
Thank you very much for your help. I will keep you informed of further steps
