### ISSUE TITLE
Map-Notify to eTR

### ISSUE THREAD

**Issue by Bystrykha** [farinacci/lispers.net#27]
Hello, Dino!
Scenario: 
    xTR_1 (first dyn. eid location) : 192.168.56.102
    xTR_2 (second dyn. eid location) : 192.168.56.111
    dyn eid: 192.168.3.5
    Dyn. eid moves fron xTR_1 to xTR_2, and I want the record about dyn. eid to be deleted from xTR_1, so that it won't send this record in Map_register.

I have problem with map-notify message to the previous destination of a dynamic eid: I changed LISP_DEFAULT_DYN_EID_TIMEOUT to 70 seconds (to check reaction to Map-Notify after dynamic eid move). Ater dyn. eid moves I get Map-Notify with its new location.
![image](https://github.com/farinacci/lispers.net/assets/59131326/a98c8ab2-4a93-4a60-addb-13e90cfdccbf)
But next Map-Register from xTR_1 contains this dyn. eid record:
![image](https://github.com/farinacci/lispers.net/assets/59131326/fdd10600-1dd7-44f1-b88f-3e7bfba989f3)
Am I missed some configuration or there is problem with Map-Notify parsing in eTR?
Here is log of lisp-etr with processing of this notify 
![image](https://github.com/farinacci/lispers.net/assets/59131326/a11cf419-5a8d-4efe-808e-54dc0a4db2dc)

**Comment by farinacci** [comment]
So there are a few things that need commenting:

(1) The dynamic-EID state in XTR_1 will go away when there is inactivity timeout. I see you changed that constant to be shorter. Did that not work for you? And are you sure you compiled the entire subsystem and was running with the new value?

(2) The Map-Notify messages you were using in the last bug report (I assume you are using the same configuration and haven't jumped to a new project) was used solely as an acknowledgment to the Map-Register. If you want to use Map-Notify messages for PubSub you need to use "send-subscribe" in a static map-cache entry you configure.

(3) The ECM (encapsulated Map-Request) SHOULD NOT be going to a multicast address. It should a unicast address of a map-resolver (that can be co-located with a map-server). So that needs to be fixed.

(4) The Map-Notify message you highlighted with RLOC 192.168.56.111 is correct. The map-server is indicating what is the latest RLOC-set for the RLOC-set change that happened when the EID moved and was registered by XTR_2.

(5) If an xTR gets a map-notify for an EID that is not in the map-cache, it means it is not interested in an RLOC-set change for the EID. That is what the message indicates. And since you did not have a subscription request in xTR_2, hence the message.

Dino
